services:

  localRabbitMQ1:
    hostname: localRabbitMQ
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"

  sender:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8177:8177"

  recipient:
    build: ./Micro
    restart: always
    volumes:
      - ./Micro:/app
    ports:
      - "8080:8080"